"""Regenerate references/design-reference-index.md from a local clone of
https://github.com/scroobius-pip/fudge-design-md.

Usage: python build_reference_index.py <path-to-fudge-design-md-clone> [output-path]

The index is one line per guide (domain plus the first sentence of the upstream
summary) so the skill can shortlist real references without fetching the upstream
README (~2,300 lines, image-heavy). Provenance is stamped in the header. The script
aborts rather than write a partial, empty, or unattributable index.
"""

import re
import subprocess
import sys
from pathlib import Path

# Windows cp1252 consoles crash printing the curly quotes and dashes that appear in
# upstream summaries (same failure devibe_scan.py patched).
sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

START = "<!-- DESIGN_MD_INDEX_START -->"
END = "<!-- DESIGN_MD_INDEX_END -->"
RAW_BASE = "https://raw.githubusercontent.com/scroobius-pip/fudge-design-md/main/design-md/"
NO_SUMMARY = "(no summary in upstream index)"


def first_sentence(text):
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text).strip()
    parts = re.split(r"(?<=\.)\s+(?=[A-Z“\"'])", text)
    out = ""
    for part in parts:
        out = (out + " " + part).strip()
        if len(out) >= 40:
            break
    return out


def parse_entries(readme_text):
    if START not in readme_text or END not in readme_text:
        sys.exit(
            f"ERROR: index markers not found in README ({START} / {END}). "
            "Upstream format has changed; aborting without writing."
        )
    block = readme_text.split(START, 1)[1].split(END, 1)[0]
    entries = []
    for section in block.split("\n### ")[1:]:
        lines = section.splitlines()
        domain = lines[0].strip()
        summary_lines = []
        for line in lines[1:]:
            s = line.strip()
            if summary_lines:
                if not s:
                    break
                summary_lines.append(s)
                continue
            if not s or s.startswith(("[![", "<!--", "#", "[Open guide]")):
                continue
            summary_lines.append(s)
        summary = first_sentence(" ".join(summary_lines)) if summary_lines else NO_SUMMARY
        entries.append((domain, summary))
    return entries


def main():
    if len(sys.argv) < 2:
        sys.exit("Usage: python build_reference_index.py <fudge-design-md-clone> [output-path]")
    clone = Path(sys.argv[1])
    readme = clone / "README.md"
    guides_dir = clone / "design-md"
    if not readme.is_file() or not guides_dir.is_dir():
        sys.exit(f"ERROR: {clone} is not a fudge-design-md clone (README.md or design-md/ missing).")

    out_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else Path(__file__).resolve().parent.parent / "references" / "design-reference-index.md"
    )

    proc = subprocess.run(
        ["git", "-C", str(clone), "log", "-1", "--format=%h %cs"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        sys.exit("ERROR: could not read the clone's commit for provenance; aborting without writing.")
    commit, commit_date = proc.stdout.strip().split()

    entries = parse_entries(readme.read_text(encoding="utf-8"))
    if not entries:
        sys.exit("ERROR: zero entries parsed from the README index; aborting without writing.")
    placeholders = [d for d, s in entries if s == NO_SUMMARY]
    if len(placeholders) > len(entries) / 5:
        sys.exit(
            f"ERROR: {len(placeholders)}/{len(entries)} entries have no parseable summary — "
            "parser no longer matches upstream format; aborting without writing."
        )

    guide_files = {p.stem for p in guides_dir.glob("*.md")}
    indexed = {d for d, _ in entries}
    missing_files = sorted(indexed - guide_files)
    unindexed = sorted(guide_files - indexed)

    lines = [
        "# Design reference index — fudge-design-md",
        "",
        "Generated by scripts/build_reference_index.py — do not hand-edit.",
        f"Source: https://github.com/scroobius-pip/fudge-design-md (MIT), commit {commit}, {commit_date}.",
        f"{len(entries)} guides. Fetch one in full:",
        "",
        f"    {RAW_BASE}<domain>.md",
        "",
        "How to choose and use one: [picking-a-reference.md](picking-a-reference.md).",
        "",
    ]
    lines += [f"- **{domain}** — {summary}" for domain, summary in entries]
    if missing_files:
        lines += ["", "## Indexed upstream but guide file missing at generation time", ""]
        lines += [f"- {d}" for d in missing_files]
    if unindexed:
        lines += [
            "",
            "## Guide files not in the upstream index",
            "",
            "Upstream leaves thin drafts out of its index; listed here so nothing is dropped silently.",
            "",
        ]
        lines += [f"- {d}" for d in unindexed]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    print(f"Wrote {out_path}")
    print(
        f"entries={len(entries)} no_summary={len(placeholders)} "
        f"indexed_without_file={len(missing_files)} files_not_indexed={len(unindexed)}"
    )
    for d in placeholders:
        print(f"  no summary: {d}")


if __name__ == "__main__":
    main()
